-- Seed tricks data
INSERT INTO tricks (name, difficulty) VALUES
('Kickflip', 4),
('Heelflip', 4),
('Treflip', 7),
('Varial Kickflip', 5),
('Varial Heelflip', 5),
('Frontside 180', 3),
('Backside 180', 3),
('Frontside 360', 8),
('Backside 360', 8),
('Hardflip', 11),
('Inward Heelflip', 10),
('Bigspin', 9),
('Bigspin Flip', 11),
('Fakie Bigspin', 9),
('Switch Bigspin', 10),
('Kickflip Backside Noseblunt', 11),
('Kickflip Frontside Boardslide', 7),
('Backside Lipslide', 7),
('Frontside Lipslide', 7),
('Smith Grind', 8),
('Feeble Grind', 8),
('Crooked Grind', 9),
('Nosegrind', 6),
('Bluntslide', 9),
('Noseblunt', 10),
('50-50', 5),
('5-0', 6),
('Manual', 4),
('Nose Manual', 5),
('Ollie', 2),
('Nollie', 3),
('Fakie Ollie', 2),
('Switch Ollie', 3),
('Kickflip to Fakie', 6),
('Kickflip Out', 6),
('Heelflip Out', 6),
('Backside Flip', 9),
('Frontside Flip', 9),
('Laser Flip', 12),
('Hospital Flip', 12),
('Hardflip Late Flip', 13),
('Treflip Late Flip', 12),
('Backside Noseblunt', 11),
('Frontside Noseblunt', 11),
('Switch Backside Lipslide', 9),
('Switch Frontside Lipslide', 9),
('Fakie Backside Smith', 9),
('Switch Crooked', 10),
('Switch Bluntslide', 10),
('Kickflip to BS Smith', 12),
('Kickflip to FS Boardslide', 9),
('Gap Ollie', 6),
('Big Gap Kickflip', 10),
('Drop In Big', 11),
('NBD Trick Example', 15),
('Technical Rail Combo Example', 13),
('Manual to Flip Out', 8),
('Flip to Fakie Manual', 9),
('Switch Flip to Nosegrind', 12),
('360 Flip', 12),
('360 Hardflip', 14);
